site_name: Ultimate Guide to UAA by Stark & Wayne
nav:
  - Guide:
    - Introduction: index.md
    - Upstream Issues: upstream-issues.md
    - Install uaa CLI: install-cli.md
    - Deploy UAA: deploy-uaa.md
    - Basic Operations: basic-operations.md
    - UAA and Client Apps: uaa-and-client-apps.md
    - Users: users.md
    - Authenticating User with Password: authenticating-user-via-password.md
    - Authenticating User via Web UI: authenticating-user-via-authcode.md
    - Real World Examples: realworld-examples.md
    - API Authentication: api-authentication.md
    - Simple Web Client: simple-web-client.md
    - User Permissions: user-permissions.md
    - Real-world UAA Client Examples: real-world-client-examples.md
    - Client Permissions: client-permissions.md
    - OpenID: openid.md
    - JSON Web Token / JWT: json-web-token.md
    - Refresh Tokens: refresh-tokens.md
    - Integrate UAA and Google Apps: integration-google-apps.md
    - Frequently Asked Questions: faq.md
  - Case Study Cloud Foundry:
    - UAA Clients: case-study-cf/uaa-clients.md
    - cloud_controller_username_lookup: case-study-cf/cloud_controller_username_lookup.md
    - cc_service_key_client: case-study-cf/cc_service_key_client.md
    - cc-service-dashboards: case-study-cf/cc-service-dashboards.md
theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

  logo: 'images/favicon/favicon-64.png'

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc:
      permalink: true

repo_name: 'help fix the tutorials'
repo_url: 'https://github.com/starkandwayne/ultimate-guide-to-uaa'
edit_uri: edit/master/docs/
extra_css: [print.css]
# google_analytics: ['UA-50822525-6', 'concoursetutorial.com']
